<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="OpportunityContactAssociationProvider"
     targetNamespace="http://xmlns.oracle.com/Application1/OpportunityContactAssociationProvider/OpportunityContactAssociationProvider"
     xmlns:ns2="http://schemas.oracle.com/bpel/extension"
     xmlns:ns1="http://www.intel.org/OpportunityContactAssociationProv/v1.0"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/Application1/OpportunityContactAssociationProvider/OpportunityContactAssociationProvider"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="OpportunityContactAssociationProvider">
        <plnk:role name="OpportunityContactAssociationProviderProvider">
            <plnk:portType name="client:OpportunityContactAssociationProvider"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="oramds:/apps/SOA-INFRA/COMMON/RuntimeFault.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.intel.org/OpportunityContactAssociationProv/v1.0" schemaLocation="oramds:/apps/SOA-INFRA/XSD/OpportunityContactAssociationProv.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="OpportunityContactAssociationProviderRequestMessage">
        <wsdl:part name="payload" element="ns1:OptyContactAssociationRequest"/>
    </wsdl:message>
    <wsdl:message name="OpportunityContactAssociationProviderResponseMessage">
        <wsdl:part name="payload" element="ns1:OptyContactAssociationResponse"/>
    </wsdl:message>
    <wsdl:portType name="OpportunityContactAssociationProvider">
        <wsdl:operation name="process">
            <wsdl:input message="client:OpportunityContactAssociationProviderRequestMessage"/>
            <wsdl:output message="client:OpportunityContactAssociationProviderResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
