<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="SFEndpointProcess"
                  targetNamespace="http://SalesforceProject/SFEndpointProcess"
                  xmlns:ns2="urn:enterprise.soap.sforce.com"
                  xmlns:ns1="urn:enterprise.soap.sforce.com"
                  xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                  xmlns:ns3="http://SFEndpoint/url"
                  xmlns:client="http://SalesforceProject/SFEndpointProcess"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <plnk:partnerLinkType name="SFEndpointProcess">
        <plnk:role name="SFEndpointProcessProvider"
                   portType="client:SFEndpointProcess"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="urn:enterprise.soap.sforce.com"
                 location="oramds:/apps/WSDL/generateEnterprise.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="urn:enterprise.soap.sforce.com"
                xmlns:ns1="urn:enterprise.soap.sforce.com"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://SalesforceProject/SFEndpointProcess"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://SalesforceProject/SFEndpointProcess"
                    schemaLocation="oramds:/apps/SOA-INFRA/XSD/SFEndpointProcess.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="urn:enterprise.soap.sforce.com"
                        schemaLocation="oramds:/apps/XSD/common/SFSessionHeader.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://SFEndpoint/url"
                        schemaLocation="oramds:/apps/XSD/common/ServiceEndpoints.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="SFEndpointProcessRequestMessage">
        <wsdl:part name="HeadersParams" element="client:process"/>
        <wsdl:part name="cudRequest" element="ns2:create"/>
        <wsdl:part name="retrieveRequest" element="ns2:retrieve"/>
        <wsdl:part name="deleteRequest" element="client:DeleteRequest"/>
        <wsdl:part name="mergeRequest" element="ns2:merge"/>
    </wsdl:message>
    <wsdl:message name="SFEndpointProcessResponseMessage">
        <wsdl:part name="cudResponse" element="ns2:createResponse"/>
        <wsdl:part name="queryResponse" element="ns2:queryResponse"/>
        <wsdl:part name="deleteResponse" element="ns2:deleteResponse"/>
        <wsdl:part name="retrieveResponse" element="ns2:retrieveResponse"/>
        <wsdl:part name="HeadersResp" element="client:processResponse"/>
        <wsdl:part name="mergeResponse" element="ns2:mergeResponse"/>
    </wsdl:message>
    <wsdl:message name="sess_and_URL_key_msg">
        <wsdl:part name="part" element="client:sessURLPlaceholder"/>
    </wsdl:message>
    <wsdl:portType name="SFEndpointProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:SFEndpointProcessRequestMessage"/>
            <wsdl:output message="client:SFEndpointProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
