<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../SFtoSiebelOpportunitySync.wsdl"/>
      <rootElement name="process" namespace="http://xmlns.oracle.com/QuoteIntegration/SFtoSiebelOptyrealTimeSync/SFtoSiebelOpportunitySync"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/SOA-INFRA/WSDL/SFEndpointProcess.wsdl"/>
      <rootElement name="process" namespace="http://SalesforceProject/SFEndpointProcess"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [THU JUN 02 12:27:02 CDT 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns0="http://SalesforceProject/SFEndpointProcess"
                xmlns:ns3="http://SFEndpoint/url"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="urn:enterprise.soap.sforce.com"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:client="http://xmlns.oracle.com/QuoteIntegration/SFtoSiebelOptyrealTimeSync/SFtoSiebelOpportunitySync"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plnk xsd wsdl client ns0 ns3 ns2 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:template match="/">
    <ns0:process>
      <ns0:Operation>
        <xsl:text disable-output-escaping="no">Query</xsl:text>
      </ns0:Operation>
      <ns0:CallerID>
        <xsl:text disable-output-escaping="no">SFtoSiebelOpportunitySync</xsl:text>
      </ns0:CallerID>
      <ns0:queryString>
        <xsl:value-of select="concat(&quot;SELECT AccountId,Amount,convertCurrency(amount) USDValue,CloseDate,RFP__c,Competitor__c,CreatedById,CreatedDate,Description,ForecastCategory,Id,LastModifiedById,LastModifiedDate,LeadSource,Legacy_Id__c,Name,CurrencyIsoCode,Type,OwnerId,Route_to_Market__c,StageName,Total_Amount__c,Upside_Amount__c,Delete_Status__c,Sales_Comment__c,Won_Lost_Reason__c,Related_Opportunity__c,Promotion_Code__c,Promotion_End_Date__c,(SELECT CreatedById,CreatedDate,CurrencyIsoCode,Description,Id,IsDeleted,LastModifiedById,LastModifiedDate,ListPrice,Name,OpportunityId,Legacy_Id__c,Opportunity_Legacy_Id__c,PricebookEntryId,Product2Id,ProductCode,Product_Type__c,Program_Type__c,Program_Benefit__c,Quantity,ServiceDate,SortOrder,SystemModstamp,TotalPrice,UnitPrice FROM OpportunityLineItems),(SELECT Id,Partner_Visibility__c,Opportunity__c,Partner_Account_Id__c,Primary__c,Disti_Locked__c,Program_Benefit__c,PBR_Active__c,Approved_Product_Types__c,Partner_Expiration_Date__c  FROM Opportunity_Partners__r)  
 FROM Opportunity WHERE Id='&quot;,/client:process/client:OpportunityId,&quot;'&quot;)"/>
      </ns0:queryString>
      <ns0:allOrNoneFlg>
        <xsl:text disable-output-escaping="no">false</xsl:text>
      </ns0:allOrNoneFlg>
      <ns0:upsertFieldName>
        <xsl:text disable-output-escaping="no"></xsl:text>
      </ns0:upsertFieldName>
    </ns0:process>
  </xsl:template>
</xsl:stylesheet>
