<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/WSDL/generateEnterprise.wsdl"/>
      <rootElement name="queryResponse" namespace="urn:enterprise.soap.sforce.com"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/WSDL/ISG_SF_Opportunity_WS.wsdl"/>
      <rootElement name="ListOfIsg_Sf_Opportunity_Io" namespace="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Query"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [TUE MAY 17 10:03:04 CDT 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsdLocal1="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Data"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:xsdLocal2="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Id"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns1="http://siebel.com/webservices"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:tns="urn:enterprise.soap.sforce.com"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://siebel.com/CustomUI"
                xmlns:xsdLocal3="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Query"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:fns="urn:fault.enterprise.soap.sforce.com"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ens="urn:sobject.enterprise.soap.sforce.com"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap tns fns xsd ens xsdLocal1 xsdLocal2 tns1 soapenc ns0 xsdLocal3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <xsl:variable name="singleQuote">'</xsl:variable>
    <xsdLocal3:ListOfIsg_Sf_Opportunity_Io>
      <xsdLocal3:Opportunity>
      <xsl:choose>
      
        <xsl:when test="string-length(/tns:queryResponse/tns:result/tns:records/ens:Legacy_Id__c)!='0'">
          <xsdLocal3:Id>
            <xsl:value-of select='concat("=",$singleQuote,/tns:queryResponse/tns:result/tns:records/ens:Legacy_Id__c,$singleQuote)'/>
          </xsdLocal3:Id>
        </xsl:when>
        <xsl:otherwise>
        <xsdLocal3:Id>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </xsdLocal3:Id>
        </xsl:otherwise>
        </xsl:choose>
        <xsdLocal3:ListOfRevenue>
          <xsdLocal3:Revenue>
            <xsl:attribute name="Searchspec">
              <xsl:value-of select='concat("[","Summary2","]","=",$singleQuote,"N",$singleQuote)'/>
            </xsl:attribute>
            <xsdLocal3:Id>
              <xsl:text disable-output-escaping="no"></xsl:text>
            </xsdLocal3:Id>
            <xsdLocal3:ISGSFId>
              <xsl:text disable-output-escaping="no"></xsl:text>
            </xsdLocal3:ISGSFId>
			 <xsdLocal3:NAIGrantNumber>
              <xsl:text disable-output-escaping="no"></xsl:text>
            </xsdLocal3:NAIGrantNumber>
          </xsdLocal3:Revenue>
        </xsdLocal3:ListOfRevenue>
        <xsdLocal3:ListOfOpportunity_Organization>
          <xsdLocal3:Opportunity_Organization>
            <xsdLocal3:Id>
              <xsl:text disable-output-escaping="no"></xsl:text>
            </xsdLocal3:Id>            
          </xsdLocal3:Opportunity_Organization>
        </xsdLocal3:ListOfOpportunity_Organization>
      </xsdLocal3:Opportunity>
    </xsdLocal3:ListOfIsg_Sf_Opportunity_Io>
  </xsl:template>
</xsl:stylesheet>
