<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="http://sfintegration-dev.corpzone.internalzone.com:80/soa-infra/services/default/OptyWSEndPointSiebelProcess/ISG_SF_Opportunity_WS.wsdl"/>
      <rootElement name="ListOfIsg_Sf_Opportunity_Io" namespace="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Data"/>
    </source>
    <source type="WSDL">
      <schema location="http://sfintegration-dev.corpzone.internalzone.com:80/soa-infra/services/default/OptyWSEndPointSiebelProcess/ISG_SF_Opportunity_WS.wsdl"/>
      <rootElement name="ListOfIsg_Sf_Opportunity_Io" namespace="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Data"/>
      <param name="varSblHeaderOutput.OPListOfOpty" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://sfintegration-dev.corpzone.internalzone.com:80/soa-infra/services/default/SFEndpointProcess/apps/WSDL/generateEnterprise.wsdl"/>
      <rootElement name="create" namespace="urn:enterprise.soap.sforce.com"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [MON FEB 29 14:54:31 CST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsdLocal1="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Data"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:xsdLocal2="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Id"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns1="http://siebel.com/webservices"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns0="urn:enterprise.soap.sforce.com"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://siebel.com/CustomUI"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:xsdLocal3="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Query"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:fns="urn:fault.enterprise.soap.sforce.com"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ens="urn:sobject.enterprise.soap.sforce.com"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl xsdLocal1 xsdLocal2 tns1 soapenc soap tns xsdLocal3 xsd ns0 fns ens xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="varSblHeaderOutput.OPListOfOpty"/>
  <xsl:template match="/">
    <ns0:create>
      <ns0:sObjects>
        <xsl:attribute name="xsi:type">
          <xsl:text disable-output-escaping="no">ens:Opportunity</xsl:text>
        </xsl:attribute>
        <xsl:if test="$varSblHeaderOutput.OPListOfOpty/xsdLocal1:ListOfIsg_Sf_Opportunity_Io/xsdLocal1:Opportunity/xsdLocal1:ISGSFId">
          <ens:Id>
            <xsl:value-of select="$varSblHeaderOutput.OPListOfOpty/xsdLocal1:ListOfIsg_Sf_Opportunity_Io/xsdLocal1:Opportunity/xsdLocal1:ISGSFId"/>
          </ens:Id>
        </xsl:if>
        <xsl:if test="$varSblHeaderOutput.OPListOfOpty/xsdLocal1:ListOfIsg_Sf_Opportunity_Io/xsdLocal1:Opportunity/xsdLocal1:Id">
          <ens:Legacy_Id__c>
            <xsl:value-of select="$varSblHeaderOutput.OPListOfOpty/xsdLocal1:ListOfIsg_Sf_Opportunity_Io/xsdLocal1:Opportunity/xsdLocal1:Id"/>
          </ens:Legacy_Id__c>
        </xsl:if>
      </ns0:sObjects>
      <xsl:if test="/xsdLocal1:ListOfIsg_Sf_Opportunity_Io/xsdLocal1:Opportunity/xsdLocal1:ListOfRevenue/xsdLocal1:Revenue/xsdLocal1:Id">
        <xsl:apply-templates select="/xsdLocal1:ListOfIsg_Sf_Opportunity_Io/xsdLocal1:Opportunity/xsdLocal1:ListOfRevenue/xsdLocal1:Revenue"/>
      </xsl:if>
    </ns0:create>
  </xsl:template>
  <xsl:template match="/xsdLocal1:ListOfIsg_Sf_Opportunity_Io/xsdLocal1:Opportunity/xsdLocal1:ListOfRevenue/xsdLocal1:Revenue">
    <ns0:sObjects>
      <xsl:attribute name="xsi:type">
        <xsl:text disable-output-escaping="no">ens:OpportunityLineItem</xsl:text>
      </xsl:attribute>
      <xsl:if test="xsdLocal1:ISGSFId">
        <ens:Id>
          <xsl:value-of select="xsdLocal1:ISGSFId"/>
        </ens:Id>
      </xsl:if>
      <xsl:if test="xsdLocal1:Id">
        <ens:Legacy_Id__c>
          <xsl:value-of select="xsdLocal1:Id"/>
        </ens:Legacy_Id__c>
      </xsl:if>
	  <xsl:if test="xsdLocal1:NAIGrantNumber">
        <ens:Grant_Number__c>
          <xsl:value-of select="xsdLocal1:NAIGrantNumber"/>
        </ens:Grant_Number__c>
      </xsl:if>
    </ns0:sObjects>
  </xsl:template>
</xsl:stylesheet>
