<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="http://sfintegration-dev.corpzone.internalzone.com/soa-infra/services/default/OptyWSEndPointSiebelProcess/ISG_SF_Opportunity_WS.wsdl"/>
      <rootElement name="ListOfIsg_Sf_Opportunity_Io" namespace="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Id"/>
    </source>
    <source type="WSDL">
      <schema location="http://sfintegration-dev.corpzone.internalzone.com/soa-infra/services/default/OptyWSEndPointSiebelProcess/ISG_SF_Opportunity_WS.wsdl"/>
      <rootElement name="ListOfIsg_Sf_Opportunity_Io" namespace="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Data"/>
      <param name="Invoke_OptyEndpoint_process_InputVariable.OPListOfOpty" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://sfintegration-dev.corpzone.internalzone.com/soa-infra/services/default/OptyWSEndPointSiebelProcess/ISG_SF_Opportunity_WS.wsdl"/>
      <rootElement name="ListOfIsg_Sf_Opportunity_Io" namespace="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Id"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [WED FEB 03 16:34:39 CST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsdLocal1="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Data"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:xsdLocal2="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Id"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns1="http://siebel.com/webservices"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://siebel.com/CustomUI"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:xsdLocal3="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Query"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl xsdLocal1 xsdLocal2 tns1 soapenc soap tns xsdLocal3 xsd xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="Invoke_OptyEndpoint_process_InputVariable.OPListOfOpty"/>
  <xsl:variable name="contactId"
                select="$Invoke_OptyEndpoint_process_InputVariable.OPListOfOpty/xsdLocal1:ListOfIsg_Sf_Opportunity_Io/xsdLocal1:Opportunity/xsdLocal1:ListOfOpportunity_ContactRole/xsdLocal1:Opportunity_ContactRole/xsdLocal1:Id"/>
  <xsl:template match="/">
    <xsdLocal2:ListOfIsg_Sf_Opportunity_Io>
      <xsdLocal2:Opportunity>
        <xsdLocal2:Id>
          <xsl:value-of select="/xsdLocal2:ListOfIsg_Sf_Opportunity_Io/xsdLocal2:Opportunity/xsdLocal2:Id"/>
        </xsdLocal2:Id>
        <xsdLocal2:ListOfOpportunity_ContactRole>
          <xsl:apply-templates select="/xsdLocal2:ListOfIsg_Sf_Opportunity_Io/xsdLocal2:Opportunity/xsdLocal2:ListOfOpportunity_ContactRole/xsdLocal2:Opportunity_ContactRole[not(xsdLocal2:Id = $contactId)]"/>
        </xsdLocal2:ListOfOpportunity_ContactRole>
      </xsdLocal2:Opportunity>
    </xsdLocal2:ListOfIsg_Sf_Opportunity_Io>
  </xsl:template>
  <xsl:template match="/xsdLocal2:ListOfIsg_Sf_Opportunity_Io/xsdLocal2:Opportunity/xsdLocal2:ListOfOpportunity_ContactRole/xsdLocal2:Opportunity_ContactRole">
    <xsdLocal2:Opportunity_ContactRole>
      <xsdLocal2:Id>
        <xsl:value-of select="xsdLocal2:Id"/>
      </xsdLocal2:Id>
    </xsdLocal2:Opportunity_ContactRole>
  </xsl:template>
</xsl:stylesheet>
