<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../OptyAssociationSiebelProvABCSImpl.wsdl"/>
      <rootElement name="EventsToProcess" namespace="http://www.siebel.com/xml/OptyEventsToProcessFromBroker"/>
    </source>
    <source type="WSDL">
      <schema location="../OptyAssociationSiebelProvABCSImpl.wsdl"/>
      <rootElement name="MultiIds" namespace="http://SalesforceIntegration/Opty_SFIds"/>
      <param name="VarIds" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://sfintegration-dev.corpzone.internalzone.com:80/soa-infra/services/default/OptyWSEndPointSiebelProcess/ISG_SF_Opportunity_WS.wsdl"/>
      <rootElement name="ListOfIsg_Sf_Opportunity_Io" namespace="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Id"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [THU JAN 21 12:38:01 CST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsdLocal1="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Data"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:xsdLocal2="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Id"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns1="http://siebel.com/webservices"
                xmlns:ns11="http://www.siebel.com/xml/OptyEventsToProcessFromBroker"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://SalesforceIntegration/Opty_SFIds"
                xmlns:ns1="urn:enterprise.soap.sforce.com"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://siebel.com/CustomUI"
                xmlns:xsdLocal3="http://www.siebel.com/xml/ISG_SF_Opportunity_IO/Query"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:client="http://xmlns.oracle.com/SFProject/OpportunityFromSFtoSiebel/OptyAssociationSiebelProvABCSImpl"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                 xmlns:ns100="urn:enterprise.soap.sforce.com"
                 xmlns:sf="urn:sobject.enterprise.soap.sforce.com"
                exclude-result-prefixes="xsi xsl ns11 ns2 ns1 wsdl plnk client xsd xsdLocal1 xsdLocal2 tns1 soapenc soap tns xsdLocal3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="VarIds"/>
  <xsl:template match="/">
    <xsdLocal2:ListOfIsg_Sf_Opportunity_Io>
      <!--xsdLocal2:Opportunity>
        <xsdLocal2:Id>
          <xsl:value-of select="$VarIds/ns2:MultiIds/ns2:ids/ns2:SiebelOptyId"/>
        </xsdLocal2:Id>
        <xsdLocal2:ListOfOpportunity_Organization>
          <xsdLocal2:Opportunity_Organization>
            <xsdLocal2:Id>
              <xsl:value-of select="$VarIds/ns2:MultiIds/ns2:ids/ns2:SiebelAccId"/>
            </xsdLocal2:Id>
            <xsdLocal2:ModId>
              <xsl:value-of select="/ns11:EventsToProcess/ns11:ListOfEvent/ns11:Event/ns11:EventId"/>
            </xsdLocal2:ModId>
          </xsdLocal2:Opportunity_Organization>
        </xsdLocal2:ListOfOpportunity_Organization>
      </xsdLocal2:Opportunity-->
      <xsl:apply-templates select="/ns11:EventsToProcess/ns11:ListOfEvent/ns11:Event[ns11:Operation ='Delete']"/>
    </xsdLocal2:ListOfIsg_Sf_Opportunity_Io>
  </xsl:template>
  <xsl:template match="/ns11:EventsToProcess/ns11:ListOfEvent/ns11:Event[ns11:Operation ='Delete']">
    <xsl:variable name="PartnerID" select="ns11:Document/ns100:result/sf:Id"/>
    <xsl:choose>
      <xsl:when test="((string-length($VarIds/ns2:MultiIds/ns2:ids[ns2:SFPartnerID=$PartnerID]/ns2:SiebelContactId) != 0.0)
 and (string-length($VarIds/ns2:MultiIds/ns2:ids[ns2:SFPartnerID=$PartnerID]/ns2:SiebelOptyId) != 0.0)) ">
        <xsdLocal2:Opportunity>
          <xsdLocal2:Id>
            <xsl:value-of select="$VarIds/ns2:MultiIds/ns2:ids[ns2:SFPartnerID=$PartnerID]/ns2:SiebelOptyId"/>
          </xsdLocal2:Id>
          <xsdLocal2:ListOfOpportunity_Organization>
            <xsdLocal2:Opportunity_Organization>
              <xsdLocal2:Id>
                <xsl:value-of select="$VarIds/ns2:MultiIds/ns2:ids[ns2:SFPartnerID=$PartnerID]/ns2:SiebelContactId"/>
              </xsdLocal2:Id>
            </xsdLocal2:Opportunity_Organization>
          </xsdLocal2:ListOfOpportunity_Organization>
        </xsdLocal2:Opportunity>
      </xsl:when>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>