<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../PollTermedUser.wsdl"/>
      <rootElement name="EventscdssfCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollTermedUser"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/SOA-INFRA/WSDL/SFEndpointProcess.wsdl"/>
      <rootElement name="process" namespace="http://SalesforceProject/SFEndpointProcess"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [WED AUG 16 09:23:19 IST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollTermedUser"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SFSiebel/CDSTermedUserFromMWToSF/PollTermedUser"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:client="http://SalesforceProject/SFEndpointProcess"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="urn:enterprise.soap.sforce.com"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="http://SFEndpoint/url"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/GetTermedUser"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl top tns plt wsdl xsd client ns2 ns1 plnk ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <client:process>
      <xsl:variable name="varEmail"
                    select="/top:EventscdssfCollection/top:Eventscdssf/*[local-name()='Row']/*[local-name()='Column'][@name='corporateemailtxt']"/>
      <xsl:variable name="varLegacyUserId"
                    select="/top:EventscdssfCollection/top:Eventscdssf/*[local-name()='Row']/*[local-name()='Column'][@name='idsid']"/>
      <xsl:variable name="sq">'</xsl:variable>
      <client:Operation>
        <xsl:text disable-output-escaping="no">Query</xsl:text>
      </client:Operation>
      <client:CallerID>
        <xsl:text disable-output-escaping="no">CDSToSFTermedUser</xsl:text>
      </client:CallerID>
      <client:queryString>
        <xsl:value-of select="concat('SELECT Id,userid FROM UserLogin where userid in',' (select id from user where email=',$sq,$varEmail,$sq,' and FederationIdentifier=',$sq,$varLegacyUserId,$sq,')')"></xsl:value-of>
      </client:queryString>
      <client:allOrNoneFlg>
      <!--  <xsl:text disable-output-escaping="no"></xsl:text> -->
      <xsl:value-of select="$varEmail"/>
      </client:allOrNoneFlg>
      <client:upsertFieldName>
       <!--  <xsl:text disable-output-escaping="no"></xsl:text> -->
        <xsl:value-of select="$varLegacyUserId"/>
      </client:upsertFieldName>
    </client:process>
  </xsl:template>
</xsl:stylesheet>
