<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/SOA-INFRA/WSDL/InsertProductPriceBookXREFProcess.wsdl"/>
      <rootElement name="SFLogObjectEvents" namespace="http://insecg-salesforce/sflogeventsobjects"/>
    </source>
    <source type="WSDL">
      <schema location="../../../Common%20Processes/ProcessSFLogEvents/populateBrokerdata.wsdl"/>
      <rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/populateBrokerdata"/>
      <param name="populateBrokerdata_InputVariable.InputParameters" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../Common%20Processes/ProcessSFLogEvents/updateSFLogStatus.wsdl"/>
      <rootElement name="SflogCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateSFLogStatus"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [SUN JAN 22 21:53:11 MST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns1="http://insecg-salesforce/sflogeventsobjects"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:client="http://IsecG-SFProject/InsertProductPriceBookXREFProcess"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SalesforceProject/ProcessSFLogEvents/populateBrokerdata"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateSFLogStatus"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/populateBrokerdata"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/SalesforceProject/ProcessSFLogEvents/updateSFLogStatus"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 client plt wsdl tns plnk db xsd top ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="populateBrokerdata_InputVariable.InputParameters"/>
  <xsl:template match="/">
    <top:SflogCollection>
      <xsl:for-each select="/ns1:SFLogObjectEvents/ns1:accountDeleteEvents">
        <xsl:variable name="sfLogIDInSFObject" select="ns1:SFLOGID"/>
        <xsl:variable name="sfLogIDInBrokerData"
                      select="$populateBrokerdata_InputVariable.InputParameters/db:InputParameters/db:P_EVENT_DTLS/db:P_EVENT_DTLS_ITEM[db:SFLOGID = $sfLogIDInSFObject]/db:SFLOGID"/>
        <xsl:if test="not($sfLogIDInBrokerData != '')">
        <top:Sflog>
          <top:sflogid>
            <xsl:value-of select="ns1:SFLOGID"/>
          </top:sflogid>
          <top:sfeventid>
            <xsl:value-of select="ns1:SFEVENTID"/>
          </top:sfeventid>
          <top:statusid>
            <xsl:text disable-output-escaping="no">1100</xsl:text>
          </top:statusid>
          <top:errormessage>
            <xsl:text disable-output-escaping="no">ObjectForeignKey is NULL</xsl:text>
          </top:errormessage>
          <top:brokereventid>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </top:brokereventid>
        </top:Sflog>
      </xsl:if>
      </xsl:for-each>
    </top:SflogCollection>
  </xsl:template>
</xsl:stylesheet>
