<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/WSDL/generateEnterprise.wsdl"/>
      <rootElement name="retrieveResponse" namespace="urn:enterprise.soap.sforce.com"/>
    </source>
    <source type="WSDL">
      <schema location="oramds:/apps/SOA-INFRA/WSDL/InsertProductPriceBookXREFProcess.wsdl"/>
      <rootElement name="SFLogObjectEvents" namespace="http://insecg-salesforce/sflogeventsobjects"/>
      <param name="sflog_objectevents" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../Common%20Processes/ProcessSFLogEvents/populateBrokerdata.wsdl"/>
      <rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/populateBrokerdata"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [MON JAN 23 00:19:08 MST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns1="http://insecg-salesforce/sflogeventsobjects"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:client="http://IsecG-SFProject/InsertProductPriceBookXREFProcess"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:tns="urn:enterprise.soap.sforce.com"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/SalesforceProject/ProcessSFLogEvents/populateBrokerdata"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/populateBrokerdata"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:fns="urn:fault.enterprise.soap.sforce.com"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ens="urn:sobject.enterprise.soap.sforce.com"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 client soap tns wsdl plnk fns xsd ens plt ns0 db xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="sflog_objectevents"/>
  <xsl:template match="/">
    <db:InputParameters>
      <db:P_EVENT_DTLS>
        <xsl:for-each select="/tns:retrieveResponse/tns:result">
          <xsl:variable name="AccountId" select="ens:Id"/>
          <db:P_EVENT_DTLS_ITEM>
            <db:SOURCE_TYPE>
              <xsl:text disable-output-escaping="no">CRM_SF_To_OP</xsl:text>
            </db:SOURCE_TYPE>
            <db:OBJECT_TYPE>
              <xsl:text disable-output-escaping="no">Account</xsl:text>
            </db:OBJECT_TYPE>
            <db:OBJECT_FOREIGNKEY>
              <xsl:value-of select="ens:Id"/>
            </db:OBJECT_FOREIGNKEY>
            <db:DOCUMENT>
              <xsl:value-of select="oraext:get-content-as-string(.)"/>
            </db:DOCUMENT>
            <db:OPERATION>
              <xsl:text disable-output-escaping="no">Delete</xsl:text>
            </db:OPERATION>
            <db:INT_POPULATEBROKER_FMWID>
              <xsl:text disable-output-escaping="no">1234</xsl:text>
            </db:INT_POPULATEBROKER_FMWID>
            <db:POPULATEBROKER_FMWID>
              <xsl:text disable-output-escaping="no">1234</xsl:text>
            </db:POPULATEBROKER_FMWID>
            <db:SFLOGID>
              <xsl:value-of select="$sflog_objectevents/ns1:SFLogObjectEvents/ns1:accountDeleteEvents[(ns1:OBJECTID = $AccountId)]/ns1:SFLOGID"/>
            </db:SFLOGID>
            <db:PRIORITY>
              <xsl:value-of select="$sflog_objectevents/ns1:SFLogObjectEvents/ns1:accountDeleteEvents[(ns1:OBJECTID = $AccountId)]/ns1:PRIORITY"/>
            </db:PRIORITY>
          </db:P_EVENT_DTLS_ITEM>
        </xsl:for-each>
      </db:P_EVENT_DTLS>
      <db:P_EVENT_BLOCK_DTLS>
        <xsl:for-each select="/tns:retrieveResponse/tns:result">
          <xsl:variable name="AccountId1" select="ens:Id"/>
          <xsl:if test="$AccountId1 != ''">
          <xsl:for-each select="$sflog_objectevents/ns1:SFLogObjectEvents/ns1:accountDeleteEvents">
          <xsl:if test="ns1:SFLOGID = $AccountId1">
            <xsl:variable name="sflogId" select="ns1:SFLOGID"/>
            <db:P_EVENT_BLOCK_DTLS_ITEM>
              <db:SOURCE_TYPE>
                <xsl:text disable-output-escaping="no">CRM_SF_To_OP</xsl:text>
              </db:SOURCE_TYPE>
              <db:OBJECT_TYPE>
                <xsl:text disable-output-escaping="no">Account</xsl:text>
              </db:OBJECT_TYPE>
              <db:OBJECT_FOREIGNKEY>
                              <xsl:value-of select="$AccountId1"/>
                           </db:OBJECT_FOREIGNKEY>
              <db:OPERATION>
                <xsl:text disable-output-escaping="no">Delete</xsl:text>
              </db:OPERATION>
            </db:P_EVENT_BLOCK_DTLS_ITEM>
          </xsl:if>
          </xsl:for-each>
       </xsl:if>
       
        </xsl:for-each>
      </db:P_EVENT_BLOCK_DTLS>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>
