<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../PollBrokerPartnerBooking.wsdl"/>
      <rootElement name="ObiPartnerBookingsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollBrokerPartnerBooking"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/WSDL/generateEnterprise.wsdl"/>
      <rootElement name="create" namespace="urn:enterprise.soap.sforce.com"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [MON MAR 27 02:44:42 MDT 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollBrokerPartnerBooking"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OBIEESF/PartnerBookingFusionToSF/PollBrokerPartnerBooking"
                xmlns:ns0="urn:enterprise.soap.sforce.com"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:fns="urn:fault.enterprise.soap.sforce.com"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ens="urn:sobject.enterprise.soap.sforce.com"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl top plt tns wsdl xsd soap ns0 fns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns0:create>
      <ns0:sObjects>
        <xsl:attribute name="xsi:type">
          <xsl:text disable-output-escaping="no">ens:Partner_Sales_Data__c</xsl:text>
        </xsl:attribute>
        <ens:Account_ID__r>
          <ens:Legacy_Id__c>
            <xsl:value-of select="/top:ObiPartnerBookingsCollection/top:ObiPartnerBookings/top:partnerId"/>
          </ens:Legacy_Id__c>
        </ens:Account_ID__r>
        <ens:Amount_USD__c>
            <xsl:value-of select="/top:ObiPartnerBookingsCollection/top:ObiPartnerBookings/top:netAmountUsd"/>
          </ens:Amount_USD__c>
          <ens:Integration_Key__c>
            <xsl:value-of select='concat(/top:ObiPartnerBookingsCollection/top:ObiPartnerBookings/top:partnerId,"+",/top:ObiPartnerBookingsCollection/top:ObiPartnerBookings/top:fiscalYear,"+",/top:ObiPartnerBookingsCollection/top:ObiPartnerBookings/top:fiscalMonth)'/>
          </ens:Integration_Key__c>
          <ens:Month__c>
            <xsl:value-of select="/top:ObiPartnerBookingsCollection/top:ObiPartnerBookings/top:fiscalMonth"/>
          </ens:Month__c>
          <ens:Name>
            <xsl:value-of select='concat(/top:ObiPartnerBookingsCollection/top:ObiPartnerBookings/top:fiscalYear,"-Monthly-",/top:ObiPartnerBookingsCollection/top:ObiPartnerBookings/top:fiscalMonth)'/>
          </ens:Name>
          <ens:Year__c>
            <xsl:value-of select="/top:ObiPartnerBookingsCollection/top:ObiPartnerBookings/top:fiscalYear"/>
          </ens:Year__c>
      </ns0:sObjects>
    </ns0:create>
  </xsl:template>
</xsl:stylesheet>
