<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/SOA-INFRA/WSDL/UpsertQuoteSFProvider.wsdl"/>
      <rootElement name="Modified_Quotes" namespace=""/>
    </source>
    <source type="WSDL">
      <schema location="oramds:/apps/SOA-INFRA/WSDL/XREFMultiLookUp.wsdl"/>
      <rootElement name="xrefinput" namespace="http://xmlns.oracle.com/XREFInterface"/>
      <param name="Invoke_XREFMultiLookup_OutputVariable.XREFOutput" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/WSDL/generateEnterprise.wsdl"/>
      <rootElement name="create" namespace="urn:enterprise.soap.sforce.com"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [FRI JAN 15 12:27:18 CST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:tns="urn:enterprise.soap.sforce.com"
                xmlns:client="http://xmlns.oracle.com/QuoteIntegration/QuoteIntegrationFromBrokerToSF/UpsertQuoteSFProvider"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/LatestCode/XREFInterface/XREFMultiLookUp"
                xmlns:fns="urn:fault.enterprise.soap.sforce.com"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns1="http://schemas.oracle.com/bpel/extension"
                xmlns:ns2="http://xmlns.oracle.com/XREFInterface"
                xmlns:ens="urn:sobject.enterprise.soap.sforce.com"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plnk client wsdl ns0 xsd ns1 ns2 soap tns fns ens xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="Invoke_XREFMultiLookup_OutputVariable.XREFOutput"/>
  <xsl:template match="/">
    <tns:create>
      <tns:sObjects>
        <xsl:attribute name="xsi:type">
          <xsl:text disable-output-escaping="no">ens:Quote</xsl:text>
        </xsl:attribute>
        <!--xsl:if test="$Invoke_XREFMultiLookup_OutputVariable.XREFOutput/ns2:xrefinput/ns2:operation[ns2:Name='QUOTE']/ns2:hostRowId !=''"-->
        <ens:Id>
          <xsl:value-of select="$Invoke_XREFMultiLookup_OutputVariable.XREFOutput/ns2:xrefinput/ns2:operation[ns2:recType='QUOTE']/ns2:hostRowId"/>
        </ens:Id>
        <!--/xsl:if-->
        <xsl:if test="/Modified_Quotes/Quote_Header/Quote_ID">
          <ens:Legacy_Id__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/Quote_ID"/>
          </ens:Legacy_Id__c>
        </xsl:if>
        <ens:Pricebook2Id>
          <!--xsl:text disable-output-escaping="no">01so0000003Yz8cAAC</xsl:text-->
          <xsl:value-of select="dvm:lookupValue('oramds:/apps/dvm/PriceBookID.dvm','Environment','Default','Salesforce','No Code Found')"/>
        </ens:Pricebook2Id>
        <!--xsl:if test="/Modified_Quotes/Quote_Header/start_date">
          <ens:Effective_Date__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/start_date"/>
          </ens:Effective_Date__c>
        </xsl:if-->
        <xsl:if test="/Modified_Quotes/Quote_Header/end_date">
          <ens:ExpirationDate>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/end_date"/>
          </ens:ExpirationDate>
        </xsl:if>
        <!--Legacy_Last_Modified_Date__c,Legacy_Created_Date__c Added as part of INSALES-4086-->
        <xsl:if test="/Modified_Quotes/Quote_Header/Last_Updated_Date">
          <ens:Legacy_Last_Modified_Date__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/Last_Updated_Date"/>
          </ens:Legacy_Last_Modified_Date__c>
        </xsl:if>
        <xsl:if test="/Modified_Quotes/Quote_Header/Created">
          <ens:Legacy_Created_Date__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/Created"/>
          </ens:Legacy_Created_Date__c>
        </xsl:if>
        <xsl:if test="/Modified_Quotes/Quote_Header/Created_By_Name">
          <ens:Legacy_Created_By__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/Created_By_Name"/>
          </ens:Legacy_Created_By__c>
        </xsl:if>
        <!--xsl:if test="$Invoke_XREFMultiLookup_OutputVariable.XREFOutput/ns2:xrefinput/ns2:operation[ns2:recType='OPPORTUNITY']/ns2:hostRowId !=''">
          <ens:Legacy_Opty_ID__c>
            <xsl:value-of select="$Invoke_XREFMultiLookup_OutputVariable.XREFOutput/ns2:xrefinput/ns2:operation[ns2:recType='OPPORTUNITY']/ns2:hostRowId"/>
          </ens:Legacy_Opty_ID__c>
        </xsl:if-->
        <xsl:if test="$Invoke_XREFMultiLookup_OutputVariable.XREFOutput/ns2:xrefinput/ns2:operation[ns2:recType='OPPORTUNITY']/ns2:hostRowId !=''">
          <ens:OpportunityId>
            <xsl:value-of select="$Invoke_XREFMultiLookup_OutputVariable.XREFOutput/ns2:xrefinput/ns2:operation[ns2:recType='OPPORTUNITY']/ns2:hostRowId"/>
          </ens:OpportunityId>
        </xsl:if>
        <xsl:if test="/Modified_Quotes/Quote_Header/Name">
          <ens:Name>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/Name"/>
          </ens:Name>
        </xsl:if>
        <!-- QuoteNumber uncommented for INSALES-4086-->
        <xsl:if test="/Modified_Quotes/Quote_Header/Quote_Number">
          <ens:Legacy_Quote_Number__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/Quote_Number"/>
          </ens:Legacy_Quote_Number__c>
        </xsl:if>

        <xsl:if test="/Modified_Quotes/Quote_Header/Quote_Type">
          <ens:Quote_Type__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/Quote_Type"/>
          </ens:Quote_Type__c>
        </xsl:if>
        <xsl:if test="/Modified_Quotes/Quote_Header/Status">
          <ens:Status>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/Status"/>
          </ens:Status>
        </xsl:if>
        <xsl:if test="/Modified_Quotes/Quote_Header/Currency_Code">
          <ens:Quote_Currency__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/Currency_Code"/>
          </ens:Quote_Currency__c>
        </xsl:if>

        <xsl:if test="/Modified_Quotes/Quote_Header/Promotion_Code != ''">
          <ens:Promotion__r>
            <ens:Promo_Code__c>
              <xsl:value-of select="/Modified_Quotes/Quote_Header/Promotion_Code"/>
            </ens:Promo_Code__c>
          </ens:Promotion__r>
        </xsl:if>

        <xsl:if test="/Modified_Quotes/Quote_Header/MFE_Budgetary_Quote_Flag">
          <xsl:choose>
            <xsl:when test="/Modified_Quotes/Quote_Header/MFE_Budgetary_Quote_Flag ='1'">

              <ens:Quote_Category__c>
                <xsl:text disable-output-escaping="no">Proposal</xsl:text>
              </ens:Quote_Category__c>
            </xsl:when>
            <xsl:otherwise>
              <ens:Quote_Category__c>
                <xsl:text disable-output-escaping="no">Quote</xsl:text>
              </ens:Quote_Category__c>
            </xsl:otherwise>
          </xsl:choose>
        </xsl:if>
        <!--xsl:if test="/Modified_Quotes/Quote_Header/EU_Total_HW_Disc_Pct">
          <ens:Total_Hardware_Discount__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/EU_Total_HW_Disc_Pct"/>
          </ens:Total_Hardware_Discount__c>
        </xsl:if>
        <xsl:if test="/Modified_Quotes/Quote_Header/EU_Total_SW_Disc_Pct">
          <ens:Total_Software_Discount__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/EU_Total_SW_Disc_Pct"/>
          </ens:Total_Software_Discount__c>
        </xsl:if>
        <xsl:if test="/Modified_Quotes/Quote_Header/EU_Grand_Total_Disc_Pct">
          <ens:Grand_Total_Discount__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/EU_Grand_Total_Disc_Pct"/>
          </ens:Grand_Total_Discount__c>
        </xsl:if-->
        <xsl:choose>
          <xsl:when test="/Modified_Quotes/Quote_Header/Quote_Type ='Direct'">
            <xsl:if test="/Modified_Quotes/Quote_Header/EU_Total_HW_Disc_Pct">
              <ens:Total_Hardware_Discount__c>
                <xsl:value-of select="/Modified_Quotes/Quote_Header/EU_Total_HW_Disc_Pct"/>
              </ens:Total_Hardware_Discount__c>
            </xsl:if>
            <xsl:if test="/Modified_Quotes/Quote_Header/EU_Total_SW_Disc_Pct">
              <ens:Total_Software_Discount__c>
                <xsl:value-of select="/Modified_Quotes/Quote_Header/EU_Total_SW_Disc_Pct"/>
              </ens:Total_Software_Discount__c>
            </xsl:if>
            <xsl:if test="/Modified_Quotes/Quote_Header/EU_Grand_Total_Disc_Pct">
              <ens:Grand_Total_Discount__c>
                <xsl:value-of select="/Modified_Quotes/Quote_Header/EU_Grand_Total_Disc_Pct"/>
              </ens:Grand_Total_Discount__c>
            </xsl:if>
          </xsl:when>
          <xsl:when test="/Modified_Quotes/Quote_Header/Quote_Type!='Direct'">
            <xsl:if test="/Modified_Quotes/Quote_Header/Total_Hardware_Disc">
              <ens:Total_Hardware_Discount__c>
                <xsl:value-of select="/Modified_Quotes/Quote_Header/Total_Hardware_Disc"/>
              </ens:Total_Hardware_Discount__c>
            </xsl:if>
            <xsl:if test="/Modified_Quotes/Quote_Header/Total_Software_Disc">
              <ens:Total_Software_Discount__c>
                <xsl:value-of select="/Modified_Quotes/Quote_Header/Total_Software_Disc"/>
              </ens:Total_Software_Discount__c>
            </xsl:if>
            <xsl:if test="/Modified_Quotes/Quote_Header/Grand_Total_Disc">
              <ens:Grand_Total_Discount__c>
                <xsl:value-of select="/Modified_Quotes/Quote_Header/Grand_Total_Disc"/>
              </ens:Grand_Total_Discount__c>
            </xsl:if>
          </xsl:when>
        </xsl:choose>
        <!--added one more field-->
        <ens:Purge_QLIs__c>
          <xsl:text disable-output-escaping="no">true</xsl:text>
        </ens:Purge_QLIs__c>
        <!--added one more field  MFE_Program_Level-->
        <xsl:if test="/Modified_Quotes/Quote_Header/MFE_Program_Level">
          <ens:Program_Level__c >
            <xsl:value-of select="/Modified_Quotes/Quote_Header/MFE_Program_Level"/>
          </ens:Program_Level__c >
        </xsl:if>
        <!--added one more field  NAI_Approval_Last_Name,Desc-->
        <xsl:if test="/Modified_Quotes/Quote_Header/NAI_Approval_Last_Name">
          <ens:Approver_Name__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/NAI_Approval_Last_Name"/>
          </ens:Approver_Name__c>
        </xsl:if>
        <xsl:if test="/Modified_Quotes/Quote_Header/Desc">
          <ens:Description>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/Desc"/>
          </ens:Description>
        </xsl:if>
        <xsl:if test="/Modified_Quotes/Quote_Header/EU_MSRP_Grand_Total">
          <ens:Grand_Total_End_User_MSRP__c>
            <xsl:value-of select="/Modified_Quotes/Quote_Header/EU_MSRP_Grand_Total"/>
          </ens:Grand_Total_End_User_MSRP__c>
        </xsl:if>
      </tns:sObjects>
    </tns:create>
  </xsl:template>
</xsl:stylesheet>
