<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="OptyContactAssociationSBLProvABCSImpl"
     targetNamespace="http://xmlns.oracle.com/SFProject/OpportunityFromSFtoSiebel/OptyContactAssociationSBLProvABCSImpl"
     xmlns:ns2="http://SalesforceIntegration/Opty_SFIds"
     xmlns:ns1="urn:enterprise.soap.sforce.com"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:client="http://xmlns.oracle.com/SFProject/OpportunityFromSFtoSiebel/OptyContactAssociationSBLProvABCSImpl"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns11="http://www.siebel.com/xml/OptyEventsToProcessFromBroker"
    >
    <plnk:partnerLinkType name="OptyContactAssociationSBLProvABCSImpl">
        <plnk:role name="OptyContactAssociationSBLProvABCSImplProvider" portType="client:OptyContactAssociationSBLProvABCSImpl"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="urn:enterprise.soap.sforce.com" location="oramds:/apps/WSDL/generateEnterprise.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/SFProject/OpportunityFromSFtoSiebel/OptyContactAssociationSBLProvABCSImpl"
                 schemaLocation="oramds:/apps/SOA-INFRA/XSD/OptyContactAssociationSBLProvABCSImpl.xsd"/>
        </schema>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ns10="http://www.siebel.com/xml/OptyEventsToProcessFromBroker"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://xmlns.oracle.com/SFProject/OpportunityFromSFtoSiebel/OptyContactAssociationSBLProvABCSImpl"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://SalesforceIntegration/Opty_SFIds"
             xmlns:ns1="urn:enterprise.soap.sforce.com" xmlns:ns11="http://www.siebel.com/xml/OptyEventsToProcessFromBroker">
            <import namespace="http://www.siebel.com/xml/OptyEventsToProcessFromBroker" schemaLocation="oramds:/apps/SOA-INFRA/XSD/OptyEventsFromEAIBrokerToProcess.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://SalesforceIntegration/Opty_SFIds"
             xmlns:ns1="urn:enterprise.soap.sforce.com" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:client="http://xmlns.oracle.com/SFProject/OpportunityFromSFtoSiebel/OptyContactAssociationSBLProvABCSImpl"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns11="http://www.siebel.com/xml/OptyEventsToProcessFromBroker">
            <xsd:import namespace="http://SalesforceIntegration/Opty_SFIds" schemaLocation="oramds:/apps/XSD/Opportunity/OptySF_Id.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="OptyContactAssociationSBLProvABCSImplRequestMessage">
        <wsdl:part name="payload" element="ns11:EventsToProcess"/>
    </wsdl:message>
    <wsdl:message name="OptyContactAssociationSBLProvABCSImplResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="OptyContactAssociationSBLProvABCSImpl">
        <wsdl:operation name="process">
            <wsdl:input message="client:OptyContactAssociationSBLProvABCSImplRequestMessage"/>
            <wsdl:output message="client:OptyContactAssociationSBLProvABCSImplResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>