<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../SumTotalFtpGet.wsdl"/>
      <rootElement name="recordList" namespace="http://IntelSecurity.com/File_PollSTTrainingCredit"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://sfintegration-qa.corpzone.internalzone.com:80/soa-infra/services/default/SFEndpointProcess/apps/WSDL/generateEnterprise.wsdl"/>
      <rootElement name="create" namespace="urn:enterprise.soap.sforce.com"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [MON FEB 22 10:33:43 CST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns2="http://siebel.com/webservices"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns0="urn:enterprise.soap.sforce.com"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:imp1="http://IntelSecurity.com/File_PollSTTrainingCredit"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:fns="urn:fault.enterprise.soap.sforce.com"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/Application1/STTrainingCreditToSblProcess/SumTotalFtpGet"
                xmlns:ens="urn:sobject.enterprise.soap.sforce.com"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl pc ns2 plt wsdl imp1 jca xsd tns soap ns0 fns ens xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns0:create>
      <xsl:for-each select="/imp1:recordList/imp1:record">
        <xsl:choose>
          <xsl:when test="string-length(imp1:ImportKey) != 0">
            <ns0:sObjects>
              <xsl:attribute name="xsi:type">
                <xsl:text disable-output-escaping="no">ens:Account</xsl:text>
              </xsl:attribute>
              <ens:Legacy_Id__C>
                <xsl:value-of select="substring-after(imp1:ImportKey,'GP_')"/>
              </ens:Legacy_Id__C>
              <xsl:if test=" string-length(imp1:CurrentYearCreditHours) != 0 ">
                <ens:Current_Yr_Training_Credits__c>
                  <xsl:value-of select="imp1:CurrentYearCreditHours"/>
                </ens:Current_Yr_Training_Credits__c>
              </xsl:if>
              <xsl:if test="string-length(imp1:PriorYearCreditHours) != 0">
                <ens:Previous_Yr_Training_Credits__c>
                  <xsl:value-of select="imp1:PriorYearCreditHours"/>
                </ens:Previous_Yr_Training_Credits__c>
              </xsl:if>
            </ns0:sObjects>
          </xsl:when>
        </xsl:choose>
      </xsl:for-each>
    </ns0:create>
  </xsl:template>
</xsl:stylesheet>
