<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../SyncOnPartnerAccountSFProvABCSImpl.wsdl"/>
      <rootElement name="SiebelMessage" namespace="http://www.siebel.com/xml/ISG_SF_Channel_Partner_IO"/>
    </source>
    <source type="WSDL">
      <schema location="../SyncOnPartnerAccountSFProvABCSImpl.wsdl"/>
      <rootElement name="ids" namespace="http://SalesforceIntegration/PartnerAccountIds"/>
      <param name="Var_Ids" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://sfintegration-dev.corpzone.internalzone.com:80/soa-infra/services/default/SFEndpointProcess/apps/WSDL/generateEnterprise.wsdl"/>
      <rootElement name="create" namespace="urn:enterprise.soap.sforce.com"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [FRI DEC 11 06:03:28 MST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://www.siebel.com/xml/ISG_SF_Channel_Partner_IO"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:client="http://xmlns.oracle.com/SFProject/SiebelToSFPartnerAccountIntegration/SyncOnPartnerAccountSFProvABCSImpl"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:tns="urn:enterprise.soap.sforce.com"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns2="http://SalesforceIntegration/PartnerAccountIds"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:fns="urn:fault.enterprise.soap.sforce.com"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns3="http://schemas.oracle.com/bpel/extension"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ens="urn:sobject.enterprise.soap.sforce.com"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl ns1 client wsdl ns2 plnk xsd ns3 soap tns fns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:param name="Var_Ids"/>
  <xsl:variable  name="varCountry" select="dvm:lookupValue('oramds:/apps/dvm/Country_SFToSBL.dvm','SBL', /ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ListOfChannelPartner_BusinessAddress/ns1:ChannelPartner_BusinessAddress/ns1:Country,'SALESFORCE','No Code Found')"/>
  <xsl:template match="/">
    <tns:create>
      <tns:sObjects>
        <xsl:attribute name="xsi:type">
          <xsl:text disable-output-escaping="no">ens:Account</xsl:text>
        </xsl:attribute>
        <ens:Id>
          <xsl:value-of select="$Var_Ids/ns2:ids/ns2:XREFSFAccountId"/>
        </ens:Id>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:DUNSNumber">
          <ens:Account_DUNS__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:DUNSNumber"/>
          </ens:Account_DUNS__c>
        </xsl:if>
         <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Name">
          <ens:Name>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Name"/>
          </ens:Name>
        </xsl:if>
      <!--  <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ParentAccountId">
          <ens:Account_Hierarchy__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ParentAccountId"/>
          </ens:Account_Hierarchy__c>
        </xsl:if>-->
        <xsl:if test='/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:AnnualRevenue and /ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:AnnualRevenue != ""'>
          <ens:AnnualRevenue>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:AnnualRevenue"/>
          </ens:AnnualRevenue>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:City">
          <ens:BillingCity>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:City"/>
          </ens:BillingCity>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsgsfaccountio/ns1:Account/ns1:Region!= ''">
               <ens:Geo__c>
                  <xsl:value-of select="dvm:lookupValue('oramds:/apps/dvm/region.dvm','Siebel',/ns1:SiebelMessage/ns1:ListOfIsgsfaccountio/ns1:Account/ns1:Region,'Salesforce','')"/>
               </ens:Geo__c>
            </xsl:if>
      <!--  <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Country">
          <ens:BillingCountry>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Country"/>
          </ens:BillingCountry>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:State">
          <ens:BillingState>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:State"/>
          </ens:BillingState>
        </xsl:if>-->        
       <!-- <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ListOfChannelPartner_BusinessAddress/ns1::ChannelPartner_BusinessAddress/ns1:ChannelPartner/ns1:StreetAddress">
       <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsgsfaccountio/ns1:Account/ns1:ListOfAccount_BusinessAddress/ns1:Account_BusinessAddress/ns1:State != ''">
                     /ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ListOfChannelPartner_BusinessAddress/ns1::ChannelPartner_BusinessAddress//
          <ens:BillingStreet>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:StreetAddress"/>
          </ens:BillingStreet>
        </xsl:if>-->
     <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ListOfChannelPartner_BusinessAddress/ns1:ChannelPartner_BusinessAddress/ns1:StreetAddress != ''">
               <ens:BillingStreet>
                  <xsl:value-of select='substring(concat(/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ListOfChannelPartner_BusinessAddress/ns1:ChannelPartner_BusinessAddress/ns1:StreetAddress,"&#x000d;&#x000a;",
                  /ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ListOfChannelPartner_BusinessAddress/ns1:ChannelPartner_BusinessAddress/ns1:StreetAddress2 ,"&#x000d;&#x000a;",
                  /ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ListOfChannelPartner_BusinessAddress/ns1:ChannelPartner_BusinessAddress/ns1:StreetAddress3),1,255)'/>
               </ens:BillingStreet>
            </xsl:if>
<!--  We are sending BillingCountryCode in Account. So changing to  BillingCountry to  BillingCountryCode-->       
		 <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ListOfChannelPartner_BusinessAddress/ns1:ChannelPartner_BusinessAddress/ns1:Country!=''">            
          <ens:BillingCountryCode>            
            <xsl:value-of select="$varCountry"/>
          </ens:BillingCountryCode>
        </xsl:if>        
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ListOfChannelPartner_BusinessAddress/ns1:ChannelPartner_BusinessAddress/ns1:State!=''">
          <ens:BillingState>            
            <xsl:value-of select="substring-before(dvm:lookupValue('oramds:/apps/dvm/State_SBLToSF.dvm','SBL',
            /ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ListOfChannelPartner_BusinessAddress/ns1:ChannelPartner_BusinessAddress/ns1:State,'SALESFORCE','No Code Found','Country',$varCountry),concat('-',$varCountry))"/>
          </ens:BillingState>
        </xsl:if>    
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGSFCreatedBy">
          <ens:CreatedById>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGSFCreatedBy"/>
          </ens:CreatedById>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:CurrencyCode">
          <ens:CurrencyIsoCode>
            <xsl:value-of select="dvm:lookupValue('oramds:/apps/dvm/currencycode.dvm','Siebel',/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:CurrencyCode,'Salesforce','No Code Found')"/>
          </ens:CurrencyIsoCode>
        </xsl:if>
	  <!-- commented  out as per the I-218501   	
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:BusinessProfile">
          <ens:Description>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:BusinessProfile"/>
          </ens:Description>
        </xsl:if>
      -->		
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGDiversityOption">
          <ens:Diversity_Option__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGDiversityOption"/>
          </ens:Diversity_Option__c>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MainFaxNumber">
          <ens:Fax>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MainFaxNumber"/>
          </ens:Fax>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:NAIFederalResellerFlag !=''">
          <ens:Federal_Reseller__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:NAIFederalResellerFlag"/>
          </ens:Federal_Reseller__c>
        </xsl:if>
     <!--   Commented for US3238
	 <xsl:choose>
          <xsl:when test='/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:PartnerFlag="Y"'>
            <ens:IsPartner>
              <xsl:text disable-output-escaping="no">1</xsl:text>
            </ens:IsPartner>
          </xsl:when>
          <xsl:otherwise>
            <ens:IsPartner>
              <xsl:text disable-output-escaping="no">0</xsl:text>
            </ens:IsPartner>
          </xsl:otherwise>
        </xsl:choose> -->
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGSFUpdatedBy">
          <ens:LastModifiedById>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGSFUpdatedBy"/>
          </ens:LastModifiedById>
        </xsl:if>
        <ens:Legacy_Id__c>
          <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Id"/>
        </ens:Legacy_Id__c>
        <xsl:if test='/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Employees and /ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Employees !=""'>
          <ens:NumberOfEmployees>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Employees"/>
          </ens:NumberOfEmployees>
        </xsl:if>
      <!--  <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ParentAccountId">
          <ens:ParentId>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ParentAccountId"/>
          </ens:ParentId>
        </xsl:if>-->
        <xsl:if test='$Var_Ids/ns2:ids/ns2:SFParentAcntId != "" and $Var_Ids/ns2:ids/ns2:SFParentAcntId !="NA"'>
        <ens:ParentId>
            <xsl:value-of select="$Var_Ids/ns2:ids/ns2:SFParentAcntId"/>
          </ens:ParentId>
          </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:NAIPartnerType">
          <ens:Partner_Type__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:NAIPartnerType"/>
          </ens:Partner_Type__c>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MainPhoneNumber">
          <ens:Phone>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MainPhoneNumber"/>
          </ens:Phone>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGSFSyncStatus">
          <ens:Sync_Status__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGSFSyncStatus"/>
          </ens:Sync_Status__c>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGTaxIDNum">
          <ens:Tax_ID_Number__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGTaxIDNum"/>
          </ens:Tax_ID_Number__c>
        </xsl:if>
      <!--  <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Type">
          <ens:Type>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Type"/>
          </ens:Type>
        </xsl:if>-->      
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:HomePage">
          <ens:Website>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:HomePage"/>
          </ens:Website>
        </xsl:if>
        
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:NAIOtherVerticalMarketFocus">
          <ens:Industry>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:NAIOtherVerticalMarketFocus"/>
          </ens:Industry>
        </xsl:if>
        
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:NAIHeadquartersFlag!=''">
          <ens:HQ_Flag__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:NAIHeadquartersFlag"/>
          </ens:HQ_Flag__c>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MFEMSPBand!=''">
          <ens:MSP_Pricing_Band__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MFEMSPBand"/>
          </ens:MSP_Pricing_Band__c>
        </xsl:if>
       <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:NAIYearEstablished!=''">
          <ens:Year_Established__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:NAIYearEstablished"/>
          </ens:Year_Established__c>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Alias!=''">
          <ens:Alias__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:Alias"/>
          </ens:Alias__c>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:AccountNumber!=''">
          <ens:Account_UCN__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:AccountNumber"/>
          </ens:Account_UCN__c>
        </xsl:if>      
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MFEGlobalUCN!=''">
          <ens:Global_UCN__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MFEGlobalUCN"/>
          </ens:Global_UCN__c>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MFEParentUCN!=''">
          <ens:Parent_UCN__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MFEParentUCN"/>
          </ens:Parent_UCN__c>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MFEGlobalName!=''">
          <ens:Global_Name__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:MFEGlobalName"/>
          </ens:Global_Name__c>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGMDMId!=''">
          <ens:Legacy_MDM_ID__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGMDMId"/>
          </ens:Legacy_MDM_ID__c>
        </xsl:if>
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:CustomerAccountGroup!=''">
          <ens:Customer_Account_Group__c>            
             <xsl:value-of select="dvm:lookupValue('oramds:/apps/dvm/customeraccountgroup.dvm','Siebel',/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:CustomerAccountGroup ,'Salesforce','No Code Found')"/>
          </ens:Customer_Account_Group__c>
        </xsl:if> 
        <xsl:if test="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGTaxIDNum!=''">
          <ens:Tax_ID_Number__c>
            <xsl:value-of select="/ns1:SiebelMessage/ns1:ListOfIsg_Sf_Channel_Partner_Io/ns1:ChannelPartner/ns1:ISGTaxIDNum"/>
          </ens:Tax_ID_Number__c>
        </xsl:if>                    
      </tns:sObjects>
    </tns:create>
  </xsl:template>
</xsl:stylesheet>