<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/WSDL/generateEnterprise.wsdl"/>
      <rootElement name="retrieveResponse" namespace="urn:enterprise.soap.sforce.com"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/SOA-INFRA/WSDL/ISG_SF_Contact_Service.wsdl"/>
      <rootElement name="ListOfIsgsfcontactio" namespace="http://www.siebel.com/xml/ISGSFContactIO/Data"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [WED MAR 16 17:23:30 CDT 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns1="http://siebel.com/webservices"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:tns="urn:enterprise.soap.sforce.com"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://siebel.com/CustomUI"
                xmlns:xsdLocal2="http://www.siebel.com/xml/ISGSFContactIO/Id"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xsdLocal3="http://www.siebel.com/xml/ISGSFContactIO/Query"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:fns="urn:fault.enterprise.soap.sforce.com"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsdLocal1="http://www.siebel.com/xml/ISGSFContactIO/Data"
                xmlns:ens="urn:sobject.enterprise.soap.sforce.com"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap tns fns xsd ens tns1 soapenc ns0 xsdLocal2 xsdLocal3 xsdLocal1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <xsdLocal1:ListOfIsgsfcontactio>
      <xsdLocal1:Contact>
        <xsl:attribute name="Operation">
          <xsl:text disable-output-escaping="no">update</xsl:text>
        </xsl:attribute>
        <xsdLocal1:Id>
          <xsl:text disable-output-escaping="no"></xsl:text>
        </xsdLocal1:Id>
        <xsdLocal1:Alias>
          <xsl:text disable-output-escaping="no">Test Update</xsl:text>
        </xsdLocal1:Alias>
        <xsdLocal1:ISGUserSFId>
            <xsl:value-of select="/tns:retrieveResponse/tns:result/ens:Id"/>
        </xsdLocal1:ISGUserSFId>
           <xsdLocal1:ISGSFSyncStatus>
                                 <xsl:text disable-output-escaping="no">SYNC_ON</xsl:text>
           </xsdLocal1:ISGSFSyncStatus>
        <xsl:choose>
          <xsl:when test='/tns:retrieveResponse/tns:result/ens:Legacy_User_Id__c != ""'>
            <xsdLocal1:LoginName>
              <xsl:value-of select="/tns:retrieveResponse/tns:result/ens:Legacy_User_Id__c"/>
            </xsdLocal1:LoginName>
          </xsl:when>
          <xsl:otherwise>
            <xsl:if test='/tns:retrieveResponse/tns:result/ens:UserType != ""'>
              <xsl:choose>
                <xsl:when test='/tns:retrieveResponse/tns:result/ens:UserType = "PowerPartner"'>
                  <xsdLocal1:LoginName>
                    <xsl:value-of select='concat("PP_",/tns:retrieveResponse/tns:result/ens:Email)'/>
                  </xsdLocal1:LoginName>
                </xsl:when>
              </xsl:choose>
            </xsl:if>
          </xsl:otherwise>
        </xsl:choose>
      </xsdLocal1:Contact>
    </xsdLocal1:ListOfIsgsfcontactio>
  </xsl:template>
</xsl:stylesheet>
