<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="DeleteOptySiebelProvider" targetNamespace="http://xmlns.oracle.com/SBLToMDMAccountUpsertReceiverServiceApplication/OpportunityFromSFtoSiebel/DeleteOptySiebelProvider" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns15="urn:enterprise.soap.sforce.com" xmlns:client="http://xmlns.oracle.com/SBLToMDMAccountUpsertReceiverServiceApplication/OpportunityFromSFtoSiebel/DeleteOptySiebelProvider" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
<wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://xmlns.oracle.com/SBLToMDMAccountUpsertReceiverServiceApplication/OpportunityFromSFtoSiebel/DeleteOptySiebelProvider" schemaLocation="oramds:/apps/SOA-INFRA/XSD/DeleteOptySiebelProvider.xsd"/>
</schema>
</wsdl:types>
<wsdl:message name="DeleteOptySiebelProviderRequestMessage">
<wsdl:part name="payload" element="client:process"/>
</wsdl:message>
<wsdl:message name="DeleteOptySiebelProviderResponseMessage">
<wsdl:part name="payload" element="client:processResponse"/>
</wsdl:message>
<wsdl:portType name="DeleteOptySiebelProvider">
<wsdl:operation name="process">
<wsdl:input message="client:DeleteOptySiebelProviderRequestMessage"/>
<wsdl:output message="client:DeleteOptySiebelProviderResponseMessage"/>
</wsdl:operation>
</wsdl:portType>
<plnk:partnerLinkType name="DeleteOptySiebelProvider">
<plnk:role name="DeleteOptySiebelProviderProvider" portType="client:DeleteOptySiebelProvider"/>
</plnk:partnerLinkType>
</wsdl:definitions>
